---
- name: Disable swap
  include_tasks: disable_swap.yml

- name: Docker setup
  include_tasks: docker_setup.yml

- name: Kubernetes setup
  include_tasks: kubernetes_setup.yml

- name: Calico setup
  include_tasks: calico_setup.yml

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ join_command.stdout_lines[0] }}"
    dest: "./join-command"
