---
- name: Disable swap
  include_tasks: disable_swap.yml

- name: Docker setup
  include_tasks: docker_setup.yml

- name: Kubernetes setup
  include_tasks: kubernetes_setup.yml

- name: Calico network setup
  include_tasks: calico_setup.yml

- name: Generate join command and copy to local file
  include_tasks: join_command.yml

