---
- name: Copies Wordpress files
  ansible.builtin.copy:
   src: "files"
   dest: "/home/vagrant/"
   owner: vagrant
   group: vagrant

- name: Deploys Wordpress on Kubernetes
  become: false
  ansible.builtin.command: kubectl create -f /home/vagrant/files

