---
- name: Copies Wordpress files
  ansible.builtin.copy:
   src: "files"
   dest: "/home/vagrant/"
   owner: vagrant
   group: vagrant

   #- name: Deploys Wordpress on Kubernetes
   #command: kubectl create -k /home/vagrant/files

   #- name: Go to this below URL to access WordPress after few seconds
   #debug:
   # msg: http://{{ groups['kubemaster'][0] }}:31000
